AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for creating API Gateway and Lambda function for Snowflake external functions"

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#  http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

Parameters:
  apiGatewayStageName:
    Type: "String"
    AllowedPattern: "^[-a-z0-9]+$"
    Default: "snowflake-usage-monitor-stage"
    Description: "API deployment stage"

  lambdaName:
    Type: "String"
    AllowedPattern: "^[a-zA-Z0-9]+[-a-zA-Z0-9-]+[-a-zA-Z0-9]+$"
    Default: "snowflake-usage-monitor-lambda"
    Description: "Lambda instance name"

  apiGatewayType:
    Type: "String"
    Default: "REGIONAL" 
    AllowedValues:
      - "REGIONAL"
      - "PRIVATE"
    Description: "API Gateway type to create"

  apiGatewayName:
    Type: "String"
    AllowedPattern: "^[a-zA-Z0-9]+[-a-zA-Z0-9-]+[-a-zA-Z0-9]+$"
    Default: "snowflake-usage-monitor-api"
    Description: "API Gateway instance name"

  apiGatewayIAMRoleName:
    Type: "String"
    Default: "snowflake-usage-monitor-agw-role"
    AllowedPattern: "^[a-zA-Z0-9]+[-a-zA-Z0-9-]+[-a-zA-Z0-9]+$"
    Description: "Role used with Snowflake API Integration"

  lambdaExecutionRoleName:
    Type: "String"
    Default: "snowflake-usage-monitor-lambda-role"
    AllowedPattern: "^[a-zA-Z0-9]+[-a-zA-Z0-9-]+[-a-zA-Z0-9]+$"
    Description: "Role used by the Lambda."

  sourceVpcId:
    Type: "String"
    Default: ""
    Description: "Snowflake VPC that has access to private API Gateway. Used only when creating a private API Gateway"

Conditions:
  shouldCreateRegionalGateway: 
    !Equals [!Ref apiGatewayType, "REGIONAL"]

Resources:
  apiGateway:
    Type: "AWS::ApiGateway::RestApi"
    DependsOn : apiIAMRole
    Properties:
      Name: !Ref "apiGatewayName"
      Description: "Snowflake external functions Gateway"
      Policy: !Sub  
          - '{ "Version": "2012-10-17", "Statement": [ {  "Effect": "Allow", "Principal": { "AWS": "arn:aws:sts::${AWS::AccountId}:assumed-role/${apiGatewayIAMRoleName}/snowflake" }, "Action": "execute-api:Invoke", "Resource": "${resourceArn}" , "Condition": { ${vpcCondition} } } ] }'
          - resourceArn : !Join [ "", [ "execute-api:/", "*" ] ]
            vpcCondition: !If 
              - shouldCreateRegionalGateway
              - ""
              - !Sub '"StringEquals": { "aws:sourceVpc": "${sourceVpcId}"}'
      EndpointConfiguration:
        Types:
          - !Ref apiGatewayType

  apiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      RestApiId: !Ref apiGateway
      ParentId: !GetAtt 
        - apiGateway
        - RootResourceId
      PathPart: slack_post
      
  apiGatewayRootMethod:
    Type: "AWS::ApiGateway::Method"
    Properties:
      AuthorizationType: "AWS_IAM"
      HttpMethod: "POST"
      Integration:
        IntegrationHttpMethod: "POST"
        Type: "AWS_PROXY"
        Uri: !Sub
          - "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${lambdaArn}/invocations"
          - lambdaArn: !GetAtt "lambdaFunction.Arn"
      ResourceId: !Ref "apiResource"
      RestApiId: !Ref "apiGateway"

  apiGatewayDeployment:
    Type: "AWS::ApiGateway::Deployment"
    DependsOn:
      - "apiGatewayRootMethod"
    Properties:
      RestApiId: !Ref "apiGateway"
      StageName: !Ref "apiGatewayStageName"

  lambdaFunction:
    Type: "AWS::Lambda::Function"
    DependsOn : lambdaExecutionIAMRole
    Properties:
      Code:
        ZipFile: |
          import json
          import requests

          def handler(event, context):
              status_code = 200
              result = []
              SLACK_URL = "https://hooks.slack.com/services/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"

              try:
                  event_body = json.loads(event["body"])
                  rows = event_body["data"]

                  for row in rows:
                      database, mtd, forecast, prior_month, change = row[1:]
                      result.append(f"{database} - MTD:{mtd} Forecast:{forecast} Prior Month:{prior_month} Change:{change.strip()}")

                  slack_message = {"text": '\n'.join(result)}
                  response = requests.post(SLACK_URL, json=slack_message)

                  if response.status_code != 200:
                      print("Failed to post to Slack. Response:", response.text)
                  else:
                      print("Slack message posted successfully")

              except Exception as err:
                  status_code = 400
                  result = event_body

              return {
                  "statusCode": status_code,
                  "body": json.dumps(result)
              }
      Description: "Echo Lambda created from CloudFormation template"
      FunctionName: !Ref "lambdaName"
      Handler: "index.handler"
      Role: !GetAtt "lambdaExecutionIAMRole.Arn" 
      Runtime: "python3.7"
      Timeout: 10

  lambdaApiGatewayInvoke:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !GetAtt "lambdaFunction.Arn"
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${apiGateway}/*/*/*"

  apiIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName : !Ref "apiGatewayIAMRoleName"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"

  lambdaExecutionIAMRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName : !Ref "lambdaExecutionRoleName"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - "sts:AssumeRole"
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"  

Outputs:
  resourceInvocationUrl:
    Value: !Sub "https://${apiGateway}.execute-api.${AWS::Region}.amazonaws.com/${apiGatewayStageName}/echo"

  awsRoleArn:
    Value: !GetAtt "apiIAMRole.Arn"
